version: '3'

services:
  frontend:
    build: ./frontend
    stdin_open: true
    tty: true
    volumes:
      - ${FRONTEND_PATH_HOST}:${FRONTEND_PATH_CONTAINER}
    command: npm start

  backend:
    build: ./backend
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_DB_USER_PASS}
      APACHE_RUN_USER: www-data
    volumes:
      - ${BACKEND_PATH_HOST}:${BACKEND_PATH_CONTAINER}
      - ./shell-scripts:${BACKEND_PATH_CONTAINER}/shell-scripts
    depends_on:
      - db
    working_dir: ${BACKEND_PATH_CONTAINER}

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_DB_USER_PASS}
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.1.1-fpm-alpine
    restart: always
    links:
      - db
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  composer:
    image: composer:2
    volumes:
      - ${BACKEND_PATH_HOST}:${BACKEND_PATH_CONTAINER}
    working_dir: ${BACKEND_PATH_CONTAINER}
    depends_on:
      - backend
    command: composer install

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - backend
      - frontend
      - phpmyadmin