version: '3'

services:
  frontend:
    build: ./frontend
    command: npm run start
    container_name: frontend
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src

  backend:
    build: ./backend
    container_name: backend
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_DB_USER_PASS}
      APACHE_RUN_USER: www-data
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ./shell-scripts:${APP_PATH_CONTAINER}/shell-scripts
    depends_on:
      - db
    ports:
      - 8080:80
    working_dir: ${APP_PATH_CONTAINER}

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_DB_USER_PASS}
    ports:
      - 6033:3306
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    links:
      - db
    ports:
      - 8081:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  composer:
    image: composer:1.6
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    depends_on:
      - backend
    command: composer install

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - backend
      - frontend