version: '3'

services:
  frontend:
    container_name: rtp_front
    image: node:14.12.0-alpine
    command: sh -c "node --stack-size=4000 /usr/local/lib/node_modules/npm/bin/npm-cli.js install && npm run start"
    stdin_open: true
    tty: true
    working_dir: /usr/app
    volumes:
      - ./frontend:/usr/app

  backend:
    container_name: rtp_back
    build: ./backend
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_DB_USER_PASS}
      APACHE_RUN_USER: www-data
    volumes:
      - ${BACKEND_PATH_HOST}:${BACKEND_PATH_CONTAINER}
      - ./shell-scripts:${BACKEND_PATH_CONTAINER}/shell-scripts
    depends_on:
      - db
    working_dir: ${BACKEND_PATH_CONTAINER}

  db:
    container_name: rtp_db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DB_USER_NAME}
      MYSQL_PASSWORD: ${MYSQL_DB_USER_PASS}
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql

  phpmyadmin:
    container_name: rtp_phpmyadmin
    image: phpmyadmin:5
    restart: always
    links:
      - db
    ports:
      - 8081:80
    depends_on:
      - db
    volumes:
      - /sessions
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1

  composer:
    image: composer:2
    volumes:
      - ${BACKEND_PATH_HOST}:${BACKEND_PATH_CONTAINER}
    working_dir: ${BACKEND_PATH_CONTAINER}
    depends_on:
      - backend
    command: composer install

  nginx:
    container_name: rtp_nginx
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - backend
      - frontend
      - phpmyadmin
